default_language_version:
    python: python3.11 # Using .python-version would be nice
repos:
    # Autoformatters
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.3.0
      hooks:
          - id: ruff
            args:
                - --fix
          - id: ruff-format
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: end-of-file-fixer
    - repo: https://github.com/jazzband/pip-tools
      rev: 7.3.0
      hooks:
          - id: pip-compile
            args:
                - --no-emit-index-url
            stages:
                - manual
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v2.7.1
      hooks:
          - id: prettier
            types_or:
                - json
                - yaml
                - toml
    - repo: https://github.com/stephen-ra-king/piptools-sync
      rev: v1.0.4
      hooks:
          - id: piptools_sync

    # Linters
    - repo: https://github.com/abravalheri/validate-pyproject
      rev: v0.15
      hooks:
          - id: validate-pyproject

    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.33.0
      hooks:
          - id: yamllint

    # Outside of the box
    - repo: local
      hooks:
          - id: gitignore
            entry: >
                bash -c 'langs={Node,Python};
                curl -s https://raw.githubusercontent.com/github/gitignore/main/$langs.gitignore >
                .gitignore'
            language: system
            name: gitignore
            pass_filenames: false
          - id: mypy
            entry: 'mypy .'
            language: system
            name: mypy
            pass_filenames: false
            stages:
                - manual
            types:
                - python
            verbose: true

          - id: pip-check
            entry: pip check
            language: system
            name: pip-check
            pass_filenames: false

          - id: shell-includes
            entry: curl -Os https://raw.githubusercontent.com/covracer/helicopyter/main/includes.sh
            language: system
            name: shell-includes
            pass_filenames: false
