---
default_language_version:
    python: python3.11 # Using .python-version would be nice
repos:
    # Autoformatters
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.0.270
      hooks:
          - id: ruff
            args:
                - --fix
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: double-quote-string-fixer
          - id: end-of-file-fixer
    - repo: https://github.com/psf/black
      rev: 23.10.1
      hooks:
          - id: black
    - repo: https://github.com/jazzband/pip-tools
      rev: 6.13.0
      hooks:
          - id: pip-compile
            args:
                - --no-emit-index-url
            stages:
                - manual
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v2.7.1
      hooks:
          - id: prettier
            types_or:
                - json
                - yaml
                - toml

    # Linters
    - repo: https://github.com/abravalheri/validate-pyproject
      rev: v0.15
      hooks:
          - id: validate-pyproject

    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.32.0
      hooks:
          - id: yamllint

    # Outside of the box
    - repo: local
      hooks:
          - id: gitignore
            entry: |
                curl -so .gitignore
                https://raw.githubusercontent.com/github/gitignore/main/Python.gitignore
            language: system
            name: gitignore
            pass_filenames: false

          - id: mypy
            entry: 'mypy .'
            language: system
            name: mypy
            pass_filenames: false
            stages:
                - manual
            types:
                - python
            verbose: true

          - id: pip-check
            entry: pip check
            language: system
            name: pip-check
            pass_filenames: false

          - id: shell-includes
            entry: curl -Os https://raw.githubusercontent.com/covracer/helicopyter/main/includes.sh
            language: system
            name: shell-includes
            pass_filenames: false
