repos:
    - repo: https://github.com/biobuddies/helicopyter
      rev: v2025.15.01
      hooks:
          - id: actionlint
          - id: codespell
            args:
                - --check-filenames
                - --check-hidden
                - --write-changes
          - id: cookiecutter
          - id: dot-yaml
          - id: hadolint
          - id: includes-sh
          - id: mailmap
          - id: mypy
          - id: prettier-write
            exclude: ^package-lock\.json$
          - id: ruff-check-fix
          - id: ruff-format
          - id: shellcheck
          - id: uv-pip-compile
            args:
                - --all-extras
                - pyproject.toml
                - requirements.in
            files: pyproject.toml
          - id: yamllint
exclude: |
    (?x)^(
        package-lock\.json
    )$
