repos:
    - repo: https://github.com/biobuddies/helicopyter
      rev: v2025.23.02
      hooks:
          # Fetch configuration for other tools
          - id: cookiecutter

          # Autoformatters may change line numbers
          - id: end-of-file-fixer
          - id: prettier-write
          - id: ruff-check-fix
          - id: ruff-format
          - id: trailing-whitespace-fixer
          - id: typos
          - id: uv-pip-compile

          # Lint last
          - id: actionlint
          - id: hadolint
          - id: mailmap
          - id: mypy
          - id: shellcheck
          - id: yamllint
exclude: |
    (?x)^(
        \.gitignore
        |package-lock\.json
    )$
