repos:
    - repo: https://github.com/biobuddies/helicopyter
      rev: v2025.23.02
      hooks:
          # Generate files
          - id: cookiecutter
          # Modify line numbers
          - id: prettier-write
          - id: ruff-check-fix
          - id: ruff-format
          - id: shfmt
          - id: uv-pip-compile
          # Report line numbers
          - id: actionlint
          - id: hadolint
          - id: mailmap
          - id: mypy
          - id: shellcheck
          - id: typos
          - id: yamllint
