repos:
    - repo: https://github.com/biobuddies/helicopyter
      rev: v2024.39.1
      hooks:
          - id: codespell
            args:
                - --check-filenames
                - --check-hidden
                - --write-changes
          - id: dot-yaml
          - id: gitignore-node-python
          - id: includes-sh
          - id: mailmap
          - id: mypy
          - id: prettier-write
          - id: ruff-check-fix
          - id: ruff-format
          - id: shellcheck
          - id: uv-pip-compile
          - id: yamllint
exclude: |
    (?x)^(
        package-lock.json
    )$
