version: '3.9'
services:
    proxy:
        image: cloudflare/cloudflared:2024.2.1

    # TODO reuse the same build for lab and web
    lab:
        build: .
        command: python -m manage shell_plus --allow-root
        depends_on:
            - postgres
        environment:
            - ALLOWEDFLARE_ACCESS_URL
            - ALLOWEDFLARE_AUDIENCE
            - ALLOWEDFLARE_EMAIL_DOMAIN
            - ALLOWEDFLARE_PRIVATE_DOMAIN
        volumes:
            - .:/srv

    postgres:
        image: postgres:15
        command: postgres -p 5501
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
        ports:
            - 5501:5501
        volumes:
            - postgres:/var/lib/postgresql/data

    web:
        build: .
        command: python -m manage runserver
        depends_on:
            - postgres
        environment:
            - ALLOWEDFLARE_ACCESS_URL
            - ALLOWEDFLARE_AUDIENCE
            - ALLOWEDFLARE_EMAIL_DOMAIN
            - ALLOWEDFLARE_PRIVATE_DOMAIN
        ports:
            # Should match manage.py
            - 8001:8001
        volumes:
            - .:/srv

networks:
    interoperation:
        name: interoperation
        external: true

volumes:
    postgres:
