services:
    proxy:
        image: cloudflare/cloudflared:2024.2.1

    hub:
        command: PATH="node_modules/.bin:$PATH" python -m jupyterhub
        depends_on:
            - postgres
        environment:
            - ALLOWEDFLARE_ACCESS_URL
            - ALLOWEDFLARE_AUDIENCE
            - ALLOWEDFLARE_EMAIL_DOMAIN
            - ALLOWEDFLARE_PRIVATE_DOMAIN
        image: allowedflare:${GASH:-local}
        volumes:
            - .:/srv
        pull_policy: never

    postgres:
        image: postgres:15
        command: postgres -p 5501
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
        ports:
            - 5501:5501
        volumes:
            - postgres:/var/lib/postgresql/data

    web:
        build: .
        command: python -m manage runserver
        depends_on:
            - postgres
        environment:
            - ALLOWEDFLARE_ACCESS_URL
            - ALLOWEDFLARE_AUDIENCE
            - ALLOWEDFLARE_EMAIL_DOMAIN
            - ALLOWEDFLARE_PRIVATE_DOMAIN
        image: allowedflare:${GASH:-local}
        ports:
            # Should match manage.py
            - 8001:8001
        volumes:
            - .:/srv
        pull_policy: never

networks:
    interoperation:
        name: interoperation
        external: true

volumes:
    postgres:
