version: 3.9
services:
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  web:
    buildit
    ports:
      - 8008:8008
    depends_on:
      - postgres

networks:
  interoperation:
    name: interoperation
    external: true

volumes:
  postgres:
