---
name: Check
run-name: Checking on behalf of ${{ github.actor }}
on: # yamllint disable-line rule:truthy
    - pull_request
jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v4

            - uses: actions/cache/restore@v4
              id: restore-pip
              with:
                  key: |
                      ${{ runner.os }}-pip
                      ${{ hashFiles('pyproject.toml') }}
                      ${{ hashFiles('requirements.in') }}
                  path: ~/.cache/pip
            - run: pip install --upgrade pip && pip install --upgrade 'pip-tools>7' && pip-sync
              env:
                  PIP_PROGRESS_BAR: 'off'
            - uses: actions/cache/save@v4
              with:
                  key: ${{ steps.restore-pip.outputs.cache-primary-key }}
                  path: ~/.cache/pip

            - uses: actions/cache/restore@v4
              id: restore-pre-commit
              with:
                  key: |
                      ${{ runner.os }}-pre-commit
                      ${{ hashFiles('.pre-commit-config.yaml') }}
                  path: ~/.cache/pre-commit
            - run: pre-commit install-hooks
            - uses: actions/cache/save@v3
              with:
                  key: ${{ steps.restore-pre-commit.outputs.cache-primary-key }}
                  path: ~/.cache/pre-commit

            - run: source includes.sh && pcam --color always --show-diff-on-failure
            - run: python -m build
            - run: twine check dist/*
            - run: python -m manage check
            - run: python -m manage makemigrations --check
            - run: docker compose build
            - run: docker compose run web python -m manage test
