defaults:
    run:
        shell: bash --noprofile --norc -o errexit -o nounset -o pipefail -o xtrace {0}
jobs:
    build-container:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: bash .biobuddies/includes.bash dcb
            - run: bash .biobuddies/includes.bash dcr web python -m manage check

    build-wheel:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: bash .biobuddies/includes.bash forceready
            - run: bash .biobuddies/includes.bash ups
            - run: source .biobuddies/includes.bash && .venv/bin/python -m build --installer=uv
            - run: .venv/bin/twine check dist/*

    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: bash .biobuddies/includes.bash forceready
            - run: |
                  PATH=".venv/bin:$PATH" \
                      bash .biobuddies/includes.bash pcam --color always --show-diff-on-failure
            - run: .venv/bin/python -m manage check
            - run: .venv/bin/python -m manage makemigrations --check

    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: bash .biobuddies/includes.bash forceready
            - run: just test

    summarize:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: bash .biobuddies/includes.bash summarize

on: # yamllint disable-line rule:truthy
    - pull_request
