jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: source includes.sh && ghas

            - uses: actions/setup-node@v4
              with:
                  cache: npm
                  node-version-file: .nvmrc
            - run: npm install --frozen-lockfile

            - uses: actions/setup-python@v5
              with:
                  python-version-file: .python-version

            - run: pip install --upgrade pip uv
              env:
                  PIP_PROGRESS_BAR: 'off'

            - run: uv venv
            - run: source includes.sh && ups && a && pcam --color always --show-diff-on-failure
            - run: .venv/bin/python -m build
            - run: .venv/bin/twine check dist/*
            - run: .venv/bin/python -m manage check
            - run: .venv/bin/python -m manage makemigrations --check
            - run: source includes.sh dcb
            # Ideally this would come from default.settings_module()
            - run: source includes.sh dcr web pytest --ds=demodj.settings

on: # yamllint disable-line rule:truthy
    - pull_request
